### ISSUE TITLE
Prettier/ESLintとeslint-config-react-appの組み合わせについて

### ISSUE THREAD

**Issue by jakenjarvis** [sadnessOjisan/blog.ojisan.io#116]
こんにちは、はじめまして。
散々、検索していた中、こちらの記事 [Prettier と ESLint の組み合わせの公式推奨が変わり plugin が不要になった](https://blog.ojisan.io/prettier-eslint-cli) を拝見させて頂きました。大変素晴らしい記事だと思います。

早速、要望なのですが、是非、以下の内容についても、記事を書いてほしいです。

 - 「[eslint-config-react-app](https://github.com/facebook/create-react-app/tree/master/packages/eslint-config-react-app#usage-outside-of-create-react-app)」との関連について
公式の [Using ESLint](https://www.gatsbyjs.com/docs/eslint/) にて、eslint-config-react-appをセットアップするように書かれていますが、これがどのように機能するのか理解できていません。（正直、Gatsbyを使う時に、eslint-config-react-appを使うべきかどうかも判断出来ていません）

 - 「.eslintrc.js」の「__PATH_PREFIX__: true」の設定について
[Using ESLint](https://www.gatsbyjs.com/docs/eslint/) の記事を見ると、Gatsby自身が使っているESLintの設定を引き継げるような内容に見えるのですが、知識不足で理解が出来ていません。

 - VSCodeを使って開発する場合のPrettier/ESLintの連携について
Editer側で別途Prettierを設定すべきということになると解釈したのですが、そうなると「.vscode\settings.json」の設定も必要になりそうだと考えてます。（まだ調べ切れてませんが、見つかるのは無効にする記事ですね）

ちなみに私は、Reactも触ったことが無いのに、Gatsbyに手を出そうとしているJAMstack初心者です。
Qiitaの記事等を見てGatsbyを使ってみたくなり、一週間前から環境準備していますが、Prettier及びESLint等のpackage.jsonの設定に納得できず、未だに環境準備中という情けない状況です。
TypeScriptはgas/claspの環境で使った経験があり、GatsbyでもTypeScriptをメインで使用するつもりでいますが、TypeScriptを使ってGatsbyを始める場合の日本語で読める記事が、圧倒的に少なく感じてます。
（内容が古くなってしまった記事か、Reactを知ってることが大前提の記事か、「なんか適当にやったら動いたからこれでいいや」みたいな記事が多い気がします）

自分にピッタリなstarterも見つからないので、苦戦してます。
日本語で相談できそうなDiscordサーバも見つけることが出来ず、相談先がどこにもないので、一番詳しく書かれていた @sadnessOjisan さんに、ちょっと甘えさせてもらう形となってしまいました（汗）
お忙しいとは思いますが、よろしくお願いいたします。

■追記
上記以外に、参照したリンクをいくつか張っておきます。
[Gatsby - issue 15971](https://github.com/gatsbyjs/gatsby/issues/15971)
[Create React App - Setting Up Your Editor](https://create-react-app.dev/docs/setting-up-your-editor/)

eslint-config-react-appを使った設定例として、唯一日本語で見れた記事として以下を挙げておきます。
[TomboMemo - GatsbyのLinter/Formatter, CSS-in-JS環境構築](https://tombomemo.com/gatsby-install-settings/)

**Comment by sadnessOjisan** [comment]
リクエストありがとうございます！ただ記事にしなくてもここで解決できそうな気がしたのでここに書いちゃいます。

> eslint-config-react-app

これは create-react-app というツールの推奨設定のはずです。
なので Gatsby に対して何かしらの関係があるツールではないですね。
React 環境下であれば、

```
npx eslint --init
```

とした後に色々質問が聞かれるのでそれに答えると設定ファイルを生成できます。

> 「.eslintrc.js」の「PATH_PREFIX: true」の設定について

引き継いでいるのは extends の効果ですね。
PATH_PREFIXは関係ないです。
global というのはそのグローバル変数の利用を許可すると言う意味ですね。

> Editer側で別途Prettierを設定すべきということになると解釈したのですが、そうなると「.vscode\settings.json」の設定も必要になりそうだと考えてます

これはそうです。確か prettier を実行するためにはプラグインも必要だったはずです。
https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

ってので解説になっていますかね？

> Qiitaの記事等を見てGatsbyを使ってみたくなり、一週間前から環境準備していますが、Prettier及びESLint等のpackage.jsonの設定に納得できず、未だに環境準備中という情けない状況です。TypeScriptはgas/claspの環境で使った経験があり、GatsbyでもTypeScriptをメインで使用するつもりでいますが、TypeScriptを使ってGatsbyを始める場合の日本語で読める記事が、圧倒的に少なく感じてます。（内容が古くなってしまった記事か、Reactを知ってることが大前提の記事か、「なんか適当にやったら動いたからこれでいいや」みたいな記事が多い気がします）

これは僕も思いますね。Gatsbyはまだ TS サポートが完璧ではないので難しいところもあると思います。
Gatsby 周りは扱っていないのですが、そういった環境構築周りについては本を書いたことがあるので、もしよろしければご購入を検討していただけると🙏

https://www.amazon.co.jp/dp/B08FWMYFTL/ref=cm_sw_r_tw_dp_x_GYZCFbBCEYFJ2

**Comment by jakenjarvis** [comment]
お返事ありがとうございます！ここで書籍を勧められるとは思いもしませんでした（笑）
でも、執筆できる程ご存じなのだと思うと、見た記事の説得力に納得です。

Gatsbyに関しては、私は仕事ではなく趣味で触ろうとしているので、書籍購入までは考えていませんでしたが、本屋さんに足を運んだ時にでも軽く拝見させて頂いて、自分のレベルにあってそうなら購入したいと思います。

※以下、長くて読みにくくなったので、章分けしました。

# eslint-config-react-appの関係性について

> なので Gatsby に対して何かしらの関係があるツールではないですね。

そうでしょうか？・・・私はまったく関係がないとは思えません。
（お忙しくて、Using ESLintのページを見られていないのかな？と思いました。ESLintの使い方を説明するページで最初の手順がおもいっきり `npm install --save-dev eslint-config-react-app` ですよ！）

書き込みから今日までの間にも、色々と調べていたのですが、eslint-config-react-appは、既にGatsbyの中に取り込まれていると思ってます。
[Using ESLint](https://www.gatsbyjs.com/docs/eslint/#how-to-use-eslint) のページに書かれている [ESLint config Gatsby ships with](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/eslint-config.ts) のリンクを辿ると、「gatsby/packages/gatsby/src/utils/eslint-config.ts」へのリンクになっており、この中でextendsに「eslint-config-react-app」を指定しています。

これ以外のGatsbyのソースを見ていないので、ここからはあちこちの記事を見た上での憶測混じりですが、「Reactのcreate-react-appで使われているeslint-config-react-app」をGatsbyも使っていて、「ESLint周りの競合問題解決を、Reactと同じようにeslint-config-react-appに丸投げしている」のではないでしょうか。

# PATH_PREFIXについて

> 引き継いでいるのは extends の効果ですね。PATH_PREFIXは関係ないです。global というのはそのグローバル変数の利用を許可すると言う意味ですね。

なるほどです。重要なのはそこではなく、```extends: `react-app` ``` のほうなのですね。
「react-appの中で、グローバル変数の__PATH_PREFIX__を参照しているので、それの参照を許可する設定」といったところでしょうか。

# 現状の最善設定を模索中
とりあえず、本来の自分のプロジェクトに依存しない形で現状の最善設定を模索するため、 [gatsby-starter-default](https://github.com/gatsbyjs/gatsby-starter-default) をForkし、 [gatsby-starter-ts-vscode-default](https://github.com/jakenjarvis/gatsby-starter-ts-vscode-default/tree/develop) を作っています。(developブランチを見てください)
普通にstarterとして使える「gatsby-starter-default＋TypeScript＋ESLint＋prettier＋stylelint(最小限)＋vscode」の環境を考えてます。（eslint-config-react-appが未対応のためes2021にするとエラーになったりと、色々はまりました。関連issue見たけどURL失念・・・）

Windows10の環境で、それっぽく動いているところまでは確認していますが、まだおかしなところがありそうです。
Lintのチェックが「何が除外されて」「何が効いている」のか、把握できていないので、結局フルで指定したほうが良いのかもしれません。
競合除外設定等やりだすと、永遠とESLintの設定をやることになりそうですが・・・本来の自分のプロジェクトで開始するときは、「eslint --init」して、全指定することになる気がします。（この時は「eslint-config-prettier」と「stylelint-config-prettier」を組み込むことになるのかな？）

いずれにしろ、お時間割いて見てもらえると嬉しいです。（変なところがあれば、ツッコミ欲しいです）

## vscodeの設定について

> これはそうです。確か prettier を実行するためにはプラグインも必要だったはずです。ってので解説になっていますかね？

はい。このあたりは、自力で調べて、それなりに形になりました。今のところこんな形になってます。
 - [.vscode/extensions.json](https://github.com/jakenjarvis/gatsby-starter-ts-vscode-default/blob/develop/.vscode/extensions.json)
 - [.vscode/launch.json](https://github.com/jakenjarvis/gatsby-starter-ts-vscode-default/blob/develop/.vscode/launch.json)
 - [.vscode/settings.json](https://github.com/jakenjarvis/gatsby-starter-ts-vscode-default/blob/develop/.vscode/settings.json)

※starterとしては、extensionsのカラー関係は除外したほうがいいですね。消すの忘れてPushしちゃいました（笑）

**Comment by sadnessOjisan** [comment]
> 「Reactのcreate-react-appで使われているeslint-config-react-app」をGatsbyも使っていて、「ESLint周りの競合問題解決を、Reactと同じようにeslint-config-react-appに丸投げしている」のではないでしょうか。

あーなるほど、分かりました。これはその認識であっています。だからこそ **Gatsby が create-react-app の設定を拝借しているだけであって、eslint-config-react-app は Gatsby に関係するものではない** です。

ただ、Gatsby 自体に ESLint を実行する機能を持たせることができて、**ビルド時にも** ESLintを使うことができます。それを可能にするのが gatsby-plugin-eslint ってやつで、このプラグインを使うときには、eslint-config-react-app を extends する必要があります。 gatsby-plugin-eslint は webpackのloaderのラッパーなので Gatsby のビルドプロセスに介入して ESLint を実行できると言うわけですね。

ただ、一般的には Lint, Format, Test は別々でやることが多いだろうし、CIのワークフロー的にもそっちの方が良いと思うので使わなくていいと思います。

そうやって Gatsby から ESLint を引き剥がすと、その設定ファイルに従う必要もなくなります。普通に `eslint src/**` みたいにするだけならどんな設定でもいいというわけですね。その公式に書かれている設定は(create-react-app の config を使いたければ再利用してもいいですが)

**Comment by jakenjarvis** [comment]
# Gatsbyとeslint-config-react-appの関係性について

> Gatsby が create-react-app の設定を拝借しているだけであって、eslint-config-react-app は Gatsby に関係するものではない

最初、私には、この一文が「矛盾を含む文章」にしか見えませんでした。
私は「eslint-config-react-appは、Gatsbyに影響を与える可能性のある構成要素（コンポーネント）の一つ」という認識です。

なので、 @sadnessOjisan さんが言いたいのは、

 - ``` eslint-config-react-app は Gatsby に関係するものではない ```

ではなく、

 - ``` eslint-config-react-app は Gatsbyプロジェクトの生産物ではない ```
 - ``` eslint-config-react-app は Gatsbyプロジェクトチームの管理範囲(責任範囲)ではない ```

ではありませんか？


# gatsby-plugin-eslintについて

> Gatsby 自体に ESLint を実行する機能を持たせることができて、ビルド時にも ESLintを使うことができます。それを可能にするのが gatsby-plugin-eslint ってやつ

なるほどです。
手元でも、gatsby-plugin-eslintを使っていない [gatsby-starter-ts-vscode-default](https://github.com/jakenjarvis/gatsby-starter-ts-vscode-default/tree/develop) で、 `gatsby build` 中にeslintが動いていないことを確認しました。


## プラグインの理解について
しかし、各プラグインの役目や使い分けって、数が多いとなかなか理解するのが大変です。
似たような名前のプラグインが多いですし、特に `gatsby-plugin-stylelint` や `postcss-css-in-js` 、`vscode-stylelint(extension)` あたりが混沌としているので、困惑しっぱなしです（笑）
歴史的経緯は、情報が分散しているので、本当に困りますね・・・。

eslint-* や tslint-* みたいな物が存在する場合もそうです。
私のような初心者は、TSLintとESLintの関係を [Roadmap: TSLint -> ESLint #4534](https://github.com/palantir/tslint/issues/4534) で知ってても、TypeScriptを使う場合に、eslintと名のつくものだけでいいのか、tslintなのか、両方必要なのか、地味に悩むのです。
実際の例としては「Emotionを使う場合に、stylelintが未対応でstyled-componentsの設定を流用する」といったケースがあるので、名前だけでは判断できないわけです。

このあたりも是非記事に！（笑）


# CIしない場合とCIする場合

> CIのワークフロー的にもそっちの方が良いと思うので使わなくていいと思います。

CIしない場合は、 `gatsby build` したときに、lintが動いてくれたほうが便利ですが、CIする場合は、package.json上でそれぞれ別コマンドとして scripts を用意しておき、CI側で `gatsby lint` と `gatsby build` を連続実行させればいいということですね。

私は「CIしない場合」しか考えていなかったので、ちょっと視野が広がった気がします。（ありがとうございます！）
CIしない場合でも、npm-run-all を使えば、同様の事が出来るので、無理にgatsby-plugin-eslintを使う必要性は無さそうですね。
（gatsby-plugin-eslintが必要になる特殊なケースはあるのでしょうけれど）


# 現状の最善設定を模索中(2)
一旦、脳内をリセットして、eslint-config-react-appを組み込まないバージョンで、 [gatsby-starter-ts-vscode-default](https://github.com/jakenjarvis/gatsby-starter-ts-vscode-default/tree/develop) の package.json構成を考えてみたいと思います。
更新したら、また、こちらでお知らせしますね。


# 記事について

> ただ記事にしなくてもここで解決できそうな気がしたのでここに書いちゃいます。

@sadnessOjisan さんが、Gatsbyの中の人でもないのに無茶振りしているのは自覚してます（笑）
ただ、Gatsbyに触れる段階で躓く部分ですので、「中身を詳しく理解している方に記事を作ってほしい」と思ったのは事実です。
私一人の解決が目的なら、DM等のクローズドな場で質問して済ませたかもしれません。
私はこのやり取りを残す事に意味があると考えています。

**Comment by sadnessOjisan** [comment]
gatsby-pluginでgatsbyのビルド時にeslintを走らせるのは、全体感を知っとかないと気づけないしドキュメントからも読み取れなさそうなので、この内容はなんかブログか何かでまとめる価値はありそうだなーと思ったので、いま書いてる記事が書き終わったら可能な限りでまとめてみます。ありがとうございますー！

**Comment by jakenjarvis** [comment]
すみません。確認した点について触れられていないので、「コイツウッゼーと華麗にスルーされた」のか、「ソウソノトオリと同意を得られた」のか分かりませんでした。

> なので、 @sadnessOjisan さんが言いたいのは、
> 　eslint-config-react-app は Gatsby に関係するものではない
> ではなく、
> 　eslint-config-react-app は Gatsbyプロジェクトの生産物ではない
> 　eslint-config-react-app は Gatsbyプロジェクトチームの管理範囲(責任範囲)ではない
> ではありませんか？

この認識であっています？
「関係する」の言葉の使い方、立ち位置、意味が異なるだけで、同じことを言ってるのだと思いました。
もし、そうではないのなら、私の認識が間違っている可能性があるので、ちゃんと確認したいです。

> いま書いてる記事が書き終わったら可能な限りでまとめてみます。

ありがとうございます！記事、期待してますね！

**Comment by sadnessOjisan** [comment]
> この認識であっています？

言いたいことはあっていそうですが、難しいところもありますね・・・
「関係する」の定義でなんとでもブレる話で、広義に捉えると関係しないものなんてないので。
「関係する」という言葉ではなく「依存」という言葉で置き換えて考えたいです。

「Gatsby のビルド機能の一つには eslint-config-react-app に依存しているものがある」と捉えた方が良いと思います。eslint-config-react-appを使わなくてもビルドは回せるのでこういう表現がまだ正確だと思います！ぼくはこの機能を使っていないので、「Gatsbyと eslint-config-react-app は関係がない」と言ってしまったのですが、それは正確ではなかったです、すみません。

**Comment by jakenjarvis** [comment]
# 「関係する」の意味について
「片方が片方になんらかの影響を与える可能性がある時、それらは関係している」と言えると思ってました。
「Gatsbyと React は関係がある」けど「Gatsbyと Vue.js は関係がない」という使い分けです。
でもこれ確かに「依存」って言葉と同義かもしれません・・・。難しいですね（汗）

# eslint-config-react-appは使っても使わなくてもいい
> eslint-config-react-appを使わなくてもビルドは回せる

Gatsbyを利用する立場だと、確かにその通りですね。

# 依存の方向性について
一般的なプラグインの仕組みで考えた場合、親は子の機能を知らなくても動かせるようにインターフェイスを取り決めます。
この場合は、「子は親に依存している」けど「親は子に依存していない」と言えると思います。

RDBのリレーションシップのように、「 **依存には方向性がある** 」と言えます。

# Gatsbyと eslint-config-react-app の関係（結論）
これをGatsbyと eslint-config-react-app の関係に置き換えると、逆転します。
[Gatsbyのソースコードの中に名前が出てくる](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/eslint-config.ts) ことから、「Gatsbyはeslint-config-react-appに依存している」と言えます。
ですが、eslint-config-react-appはおそらくReactの事は意識していますが、Gatsbyの事は意識していません。（[create-react-app](https://github.com/facebook/create-react-app) のリポジトリで [「Gatsby」を検索](https://github.com/facebook/create-react-app/search?q=Gatsby) しても、現時点ではREADME.mdとCHANGELOG-0.x.mdしか引っかかりません）

この依存の仕方は、プラグインではなく「構成要素（コンポーネント）」だと思います。
なので「 **eslint-config-react-app は、Gatsbyの構成要素（コンポーネント）の一つ** 」です。

これが私が出した結論です。

で・・・齟齬が無いように書いたつもりです。この認識で違うところがあれば、ご指摘ください。
同意を頂けると、この一週間「自分の調べたことに間違いがなかった」と自信が持てます。

**Comment by sadnessOjisan** [comment]
> eslint-config-react-app は、Gatsbyの構成要素の一つ

 はい、この捉え方で問題ないです！
