### ISSUE TITLE
READMEのCONTRIBUTEのリンクが無効になってる

### ISSUE THREAD

**Issue by kazuhitonakayama** [sadnessOjisan/blog.ojisan.io#153]
READMEのCONTRIBUTEのリンクが無効になっていた為、修正する必要があるかと感じました！

If we tap the CONTRIBUTE link in README,
![スクリーンショット 2020-12-28 19 55 23](https://user-images.githubusercontent.com/50609459/103209577-ccf3cc00-4946-11eb-9482-6970e2cf8522.png)

we access to this page
![image](https://user-images.githubusercontent.com/50609459/103209530-b483b180-4946-11eb-8c62-4538730fd691.png)

**Comment by kazuhitonakayama** [comment]
hope you will check out our PR here when you have a chance!
お手隙の際に、こちらのPRをご確認頂けば幸いです🙇‍♂️

https://github.com/sadnessOjisan/blog.ojisan.io/pull/154

@sadnessOjisan

**Comment by sadnessOjisan** [comment]
#154 mergeいたしましたっm
