### ISSUE TITLE
Re: Webサーバーアーキテクチャ進化論2023

### ISSUE THREAD

**Issue by kzys** [sadnessOjisan/blog.ojisan.io#316]
こんにちは。はじめまして。https://blog.ojisan.io/server-architecture-2023/ めちゃくちゃ良かったです。修正を送れると良いのですが、代案がないところも多々あるので、素の issue で失礼します。

> 原文を少し読むとその資料自体は「こういう問題がくるぞ、ヤバい」というテイストというよりかは、(...) とあるようにたくさんのクライアントを同時に扱う際の実装テクニックを紹介することが目的な気がする。

これは2023年に読むとそうなのですが、1999年の https://web.archive.org/web/19990508164301/http://www.kegel.com/c10k.html を読むと、実装テクニックが手薄で、問題提起の面も強かったのかと思います。当時の Linux には epoll もないし。

> Go のような軽量スレッドでコンテキストスイッチのコスト自体を抑えたりグリーンスレッドで pid, fd の枯渇を回避することができる。

pid はリサイクルされるし、fd はソケットで使ってしまうので、グリーンスレッドのところでふれなくてもよいかと思いました。

> さてそのコンテキストスイッチを自前で実装し、グリーンスレッドを実装して C10K 問題を解決したのが Go 言語だったり Rust の tokio だったり Scala の cats-effect だ。

コンテキストスイッチのアセンブリのところは全然知らない世界で面白かったです。一方で、そういう低レイヤなコンテキストスイッチや、ガードページも ABI も、tokio と cats-effect では明示的には触っていない (はず) なので、このあたりは「Go の話ですよ」と事前にもっと強調してもよいかと思いました。

**Comment by sadnessOjisan** [comment]
ありがとうございます。反応もらえて嬉しいです。

> これは2023年に読むとそうなのですが、1999年の https://web.archive.org/web/19990508164301/http://www.kegel.com/c10k.html を読むと、実装テクニックが手薄で、問題提起の面も強かったのかと思います

これ知らなかったです。今のドキュメントと違っていたのですね。2023年時点のものを読んだ時は「C10K問題って別に問題の名前ではないのか、みんな問題のように扱っているけど」と思っていたのですが、当時は違ったのですね。勉強になります。

> pid はリサイクルされるし、fd はソケットで使ってしまうので、グリーンスレッドのところでふれなくてもよいかと思いました。

たしかにマルチスレッドの話で pid や fd を出すのもおかしいですね。削除します。

> ガードページも ABI も、tokio と cats-effect では明示的には触っていない (はず) なので、このあたりは「Go の話ですよ」と事前にもっと強調してもよいかと思いました。

はい、ここではGo特有の話です。そうですね、各節でGoの話であることを明記しておきます。

コメントありがとうございましたmm

**Comment by kzys** [comment]
> これ知らなかったです。今のドキュメントと違っていたのですね。2023年時点のものを読んだ時は「C10K問題って別に問題の名前ではないのか、みんな問題のように扱っているけど」と思っていたのですが、当時は違ったのですね。勉強になります。

日本だと、2007年に、いまだと https://misreading.chat/ をしている森田さんが[翻訳していて](https://bn.dodgson.org/bn/2007/03/04/)、私も最初に読んだのは[当時のバージョン](https://web.archive.org/web/20070307073544/https://www.hyuki.com/yukiwiki/wiki.cgi?TheC10kProblem)だったような記憶があります。

**Comment by sadnessOjisan** [comment]
修正済みなので close します。ありがとうございました！
